"""End-to-end check. Needs: pip install playwright && playwright install chromium.
Run from the repo root with the app served: npm run build && npx vite preview --port 4173
Then: python3 tests/e2e/accessory-workflow.py
Screenshots and downloads go to e2e-out/."""
import os
os.makedirs("e2e-out", exist_ok=True)
from playwright.sync_api import sync_playwright
import os
with sync_playwright() as p:
    b = p.chromium.launch(args=['--use-gl=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'])
    ctx = b.new_context(viewport={'width':1366,'height':768}, accept_downloads=True)
    ctx.add_init_script("localStorage.setItem('nexo-tour-accessory-v1','1'); localStorage.setItem('nexo-tour-clothing-v1','1')")
    pg = ctx.new_page()
    errs=[]
    pg.on('console', lambda m: errs.append(m.type+': '+m.text) if m.type=='error' else None)
    pg.on('pageerror', lambda e: errs.append('PAGEERROR: '+str(e)))
    pg.goto('http://127.0.0.1:4173/')
    pg.wait_for_selector('.home')
    pg.click('text=New Project'); pg.fill('#np-name','Test Hat'); pg.click('text=Create project')
    pg.wait_for_selector('.workspace'); pg.wait_for_timeout(1500)
    print('1 project name:', pg.input_value('.project-name'))
    pg.click('button[aria-label="Add Part"]'); pg.click('.picker-item:has-text("Cube")'); pg.wait_for_timeout(500)
    print('2 selected obj name field:', pg.input_value('#obj-name'))
    inp = pg.locator('.props .numfield-input').nth(0)
    inp.fill('2.5'); inp.press('Enter'); pg.wait_for_timeout(300)
    print('3 pos X now:', pg.locator('.props .numfield-input').nth(0).input_value())
    pg.fill('.color-row input.input', '#00ff00'); pg.press('.color-row input.input','Enter'); pg.wait_for_timeout(300)
    print('3b color now:', pg.input_value('.color-row input.input'))
    pg.evaluate('document.activeElement.blur()')
    pg.keyboard.press('Control+z'); pg.wait_for_timeout(200)
    print('4 after undo color:', pg.input_value('.color-row input.input'))
    pg.keyboard.press('Control+z'); pg.wait_for_timeout(200)
    print('4b after 2nd undo posX:', pg.locator('.props .numfield-input').nth(0).input_value())
    pg.keyboard.press('Control+y'); pg.wait_for_timeout(200)
    print('4c after redo posX:', pg.locator('.props .numfield-input').nth(0).input_value())
    pg.select_option('select[aria-label="Material preset"]','gold'); pg.wait_for_timeout(200)
    pg.evaluate('document.activeElement.blur()')
    pg.keyboard.press('Control+d'); pg.wait_for_timeout(300)
    print('5 objects count:', pg.locator('.tab:has-text("Objects") .count').inner_text())
    pg.keyboard.press('Delete'); pg.wait_for_timeout(300)
    print('5b after delete:', pg.locator('.tab:has-text("Objects") .count').inner_text())
    pg.keyboard.press('Control+z'); pg.wait_for_timeout(200)
    print('5c after undo delete:', pg.locator('.tab:has-text("Objects") .count').inner_text())
    pg.click('button[aria-label="Add Hat"]'); pg.click('.picker .asset-card:has-text("Horns")'); pg.wait_for_timeout(500)
    pg.keyboard.press('w'); pg.wait_for_timeout(600)
    pg.screenshot(path='e2e-out/gizmo.png')
    pg.keyboard.press('Control+s'); pg.wait_for_timeout(800)
    print('6 status:', pg.locator('.save-status').inner_text())
    pg.click('.tab:has-text("Validation")'); pg.wait_for_timeout(300)
    pg.screenshot(path='e2e-out/validation.png')
    pg.click('button:has-text("Export")'); pg.wait_for_selector('.export-grid'); pg.wait_for_timeout(300)
    pg.screenshot(path='e2e-out/export.png')
    with pg.expect_download() as d:
        pg.click('.modal-foot .btn.primary')
    dl = d.value; path='e2e-out/'+dl.suggested_filename; dl.save_as(path)
    print('7 exported:', dl.suggested_filename, os.path.getsize(path), 'bytes; magic', open(path,'rb').read(4))
    pg.wait_for_timeout(300)
    pg.reload(); pg.wait_for_selector('.home'); pg.wait_for_timeout(500)
    print('8 after reload, projects:', pg.locator('.proj-card .proj-name').all_inner_texts())
    pg.click('.proj-card:has-text("Test Hat") .proj-open'); pg.wait_for_selector('.workspace'); pg.wait_for_timeout(1200)
    print('9 reopened objects:', pg.locator('.tab:has-text("Objects") .count').inner_text())
    print('errors:', errs[:10] or 'none')
    b.close()
